<?php include __DIR__.'/../header.html'; ?>

    <div class="container">
        <div class="row">
            <h1>Adicionar Categorias</h1>
            <h3><?= "Post -  {$post->getTitle()}" ?></h3>
            <form method="post" name="form" action="<?php echo "/posts/{$post->getId()}/set-categories"; ?>">
                <div class="form-group">
                    <label for="categories">Categories</label>
                    <select class="form-control" name="categories[]" multiple>
                        <?php foreach ($categories as $category): ?>
                            <option value="<?= $category->getId() ?>"
                                <?php echo $post->getCategories()->contains($category) ? "selected='selected'": "" ?> >
                                <?= $category->getName() ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>
<?php include __DIR__.'/../footer.html'; ?>